import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from 'next/head';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Mr Chams",
  description: "Generated by create next app",
    icons: {
    icon: "/mrChams-Logo.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/mrChams-Logo.svg" sizes="any" />
      </Head>
      <body suppressHydrationWarning={true} className="fixed-classname">
        {children}
      </body>
    </html>
  );
}
